
apps:
  - name: mudbase-new
    script: /srv/mudbase-new/backend/build/index.js
    node_args: --experimental-modules
    env:
      NODE_ENV: production
      NEXTAUTH_URL: https://new.mudbase.am
      CONFIG_FILE: config-dev.yaml

