trailingComma: es5
tabWidth: 4
printWidth: 100
useTabs: false
semi: true
singleQuote: true
quoteProps: as-needed
jsxSingleQuote: true
bracketSpacing: false
endOfLine: lf
bracketSameLine: false

overrides:
  - files: '*.js'
    options:
      tabWidth: 2
  - files: '*.json'
    options:
      tabWidth: 2
  - files: '*.html'
    options:
      tabWidth: 2
